### PR TITLE
Add more artworks from sanjose.gov

### PR DESCRIPTION
**Pull request by ctram**
- Adds ability to scrape sanjose.gov site for more artworks. 
- Merges none duplicate artworks into `art.js` file.

There are five JSON files containing the artworks:

`_legacy-art.json` - Artwork that originally existed in the `art.js` file.
`_scraped-artworks.json` - Artwork scraped without errors (missing, title, artists, coordinates)
`_scraped-artworks-errors.json` - Artwork scraped with errors.
`artworks-overrides.json` - Artwork with manually corrected data.
`consolidated-artworks.json` - "master" file containing all artworks intended to appear on the map.

`_legacy-art.json`, `_scraped-artworks.json`, `_scraped-artworks-errors.json` are intended to be read-only after they are created by the scraper.

 Any manually corrections should be done in `artworks-overrides.json`. 

There is a script `consolidate-artwork-files.js`, that will merge all the "read-only" files and `artworks-overrides.json` to created `consolidated-artworks.json`. The script works like `Object.assign`, so an artwork that already exists will be overridden the next time that artwork is merged (identified by `id` property), so the order of the files being merged matters, `artworks-overrides.json` should aways be last.

This way, if someone wants to tweak the scraper and run it again, we ensure we keep the manual corrections alive in `artworks-overrides.json`.

After `consolidated-artworks.json` is created, we can manually copy the JSON into `public/js/art.js`. Careful though, since we are moving JSON into a JS file, I believe we need to watch out for escaped characters, like `Tom said, \\"Hey!\\"`. Hasn't happened and I am pretty sure it never will since this project is just about scraping sanjose.gov, and it has already been scraped, but just a note.

### CODE REVIEW

**Comment by ctram** [comment]
@JMStudiosJoe @ychoy regarding the API key issue, I'm not familiar with a way to protect the key if it's already on the client side.

Piggy back riding on the heroku idea, I realize heroku can be slow, especially after a long sleep, but perhaps we can have the app ask for only the API key from heroku. I suppose the big issue is the Heroku server booting up after a long sleep...

**Comment by JMStudiosJoe** [comment]
what makes heroku slow? We would only scrape when needed to not every day and the server sending the keys is a small request. We would however need to start paying for the domain and heroku services so that is another downside of going to heroku.

**Comment by ctram** [comment]
@JMStudiosJoe Heroku puts a server to sleep after 30 minutes amount of time of no-requests. The next request will boot up the server which takes some time, last I checked, maybe 5 - 10 seconds, maybe that's changed.

Per https://www.heroku.com/pricing,

A verified free account (a credit card is needed) gets 1000 dyno hours; each request will use at least 30 minutes of server time, so at worse, it could handle 2000 requests per month, right? Is that reasonable?

**Comment by JMStudiosJoe** [comment]
Did not know that about Heroku thanks for that. Ya that seems reasonable for now we can try to explore it but not migrate it to Heroku till we know more. What do you think @ychoy ?

**Pull request merged**
